apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500  # You can choose from 30000-32767
