apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: iiitbroshan/backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: JWT_SECRET_KEY
              value: "{{ jwt_secret_key }}"
            - name: ENCRYPTION_KEY
              value: "{{ encryption_key }}"
            - name: ML_SERVICE_URL
              value: "{{ ml_service_url }}"
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
          volumeMounts:
            - name: backend-logs
              mountPath: /var/log/backend
      volumes:
        - name: backend-logs
          hostPath:
            path: /var/log/backend
            type: DirectoryOrCreate
