apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
        - name: ml-service
          image: roshany852k/ml-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001

