- name: Deploy ELK stack to Kubernetes
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create elk namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: elk
        state: present

    - name: Apply Elasticsearch deployment
      kubernetes.core.k8s:
        state: present
        src: ./elasticsearch-deployment.yaml

    - name: Apply Logstash ConfigMap
      kubernetes.core.k8s:
        state: present
        src: ./logstash-configmap.yaml

    - name: Apply Logstash deployment
      kubernetes.core.k8s:
        state: present
        src: ./logstash-deployment.yaml

    - name: Apply Kibana deployment
      kubernetes.core.k8s:
        state: present
        src: ./kibana-deployment.yaml
